### ISSUE TITLE
update peer dependency versions

### ISSUE THREAD

**Issue by pantoninho** [vydimitrov/react-random-reveal#12]
This package can't be installed with npm7 if you're using React17. If `react-random-reveal` is compatible with React17, could you please update the `package.json` to also support it?

Thank you!

**Comment by vydimitrov** [comment]
Hey @pantoninho, are you still interested in using this package? I can update it and polish the code :)

**Comment by vydimitrov** [comment]
By the way, I am sorry for late reply, I just thought that no one is using it.

**Comment by vydimitrov** [comment]
Hey @pantoninho, I just updated the whole package and added some new features. Go check it out!
